export * from "./protocol";
export { decodeEvent } from "./events";
export type { ConduitEvent, ConduitEventOf, EventTag } from "./events";
export { ConduitClient, termKey } from "./client";
export type { AppEvent, ConnStatus, ConduitClientOptions, TermKey, TerminalSink } from "./client";
export { createTerminal, promptInput } from "./terminal";
export type { CreateTerminalOpts, TerminalHandle } from "./terminal";
export { parseUnifiedDiff, diffLineRange, buildDiffQuestion } from "./diff";
export type { DiffFile, DiffHunk, DiffLine } from "./diff";
export { b64ToBytes, bytesToB64, textToB64 } from "./b64";
