// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BranchInfo = { name: string, is_head: boolean, ahead: number | null, behind: number | null, };
