// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An existing branch to check out into a new workspace's worktree, instead
 * of creating a fresh branch off a base ref.
 */
export type CheckoutSource = { "LocalBranch": { name: string, } } | { "RemoteBranch": { remote_ref: string, } };
