// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttentionLevel } from "./AttentionLevel";
import type { CheckoutSource } from "./CheckoutSource";
import type { Route } from "./Route";
import type { SshTarget } from "./SshTarget";
import type { TerminalKind } from "./TerminalKind";

export type Command = { "SetRoute": Route } | { "AddWorkspace": { name: string, path: string, ssh: SshTarget | null, } } | { "RemoveWorkspace": { id: string, } } | { "RenameWorkspace": { id: string, name: string, } } | { "SetWorkspaceAgent": { id: string, agent: string | null, } } | { "MoveWorkspace": { id: string, delta: number, } } | { "SetAttention": { id: string, level: AttentionLevel, } } | { "ClearAttention": { id: string, } } | { "RefreshGit": { id: string, } } | { "RunWorkspaceCommand": { id: string, command: string, } } | { "LoadDiff": { id: string, file: string, } } | { "LoadCommitDiff": { id: string, hash: string, } } | { "LoadCommitFiles": { id: string, hash: string, } } | { "LoadCommitFileDiff": { id: string, hash: string, file: string, } } | { "GitStageFile": { id: string, file: string, } } | { "GitUnstageFile": { id: string, file: string, } } | { "GitStageAll": { id: string, } } | { "GitUnstageAll": { id: string, } } | { "GitCommit": { id: string, message: string, } } | { "GitCheckoutBranch": { id: string, branch: string, } } | { "GitCheckoutRemoteBranch": { id: string, remote_branch: string, local_name: string, } } | { "GitCreateBranch": { id: string, branch: string, } } | { "GitDeleteLocalBranch": { id: string, branch: string, } } | { "GitDeleteRemoteBranch": { id: string, remote: string, branch: string, } } | { "GitPush": { id: string, } } | { "GitPull": { id: string, } } | { "GitFetch": { id: string, } } | { "GitDiscardFile": { id: string, file: string, } } | { "GitDiscardAll": { id: string, } } | { "GitStash": { id: string, message: string | null, } } | { "GitStashPullPop": { id: string, } } | { "GitStashAll": { id: string, } } | { "StartTerminal": { id: string, kind: TerminalKind, tab_id: string | null, cmd: Array<string>, 
/**
 * Initial terminal width in columns. `0` (or absent, for older
 * clients) means "use the default" so the child process is born at the
 * right size instead of a hardcoded width it has to be resized away
 * from. Spawning at the wrong width briefly leaves full-screen TUIs
 * (e.g. Claude) wrapping to a stale column count.
 */
cols: number, rows: number, } } | { "StopTerminal": { id: string, kind: TerminalKind, tab_id: string | null, } } | { "SendTerminalInput": { id: string, kind: TerminalKind, tab_id: string | null, data_b64: string, } } | { "ResizeTerminal": { id: string, kind: TerminalKind, tab_id: string | null, cols: number, rows: number, } } | { "ClearShellResurrection": { id: string, tab_id: string, } } | { "RegisterRepository": { name: string, path: string, ssh: SshTarget | null, default_agent: string | null, worktree_root: string | null, } } | { "RemoveRepository": { repo_id: string, } } | { "CreateWorkspace": { repo_id: string, name: string, base_branch: string | null, 
/**
 * Agent to launch in this Workspace: a configured profile name or a raw
 * custom command. `None` = use the client's default agent. Opaque to
 * core; interpreted by the TUI when it starts the agent terminal.
 */
agent: string | null, 
/**
 * When set, check out this existing branch instead of creating a new
 * branch off `base_branch` (which is ignored).
 */
existing: CheckoutSource | null, } } | { "ListRepoBranches": { repo_id: string, } } | { "SetReadyForReview": { id: string, ready: boolean, } } | { "LoadBranchDiff": { id: string, } } | { "LoadBranchFileDiff": { id: string, file: string, } } | { "OpenPullRequest": { id: string, } };
