// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BranchInfo } from "./BranchInfo";
import type { ChangedFile } from "./ChangedFile";
import type { CommitInfo } from "./CommitInfo";
import type { RemoteBranchInfo } from "./RemoteBranchInfo";
import type { TagInfo } from "./TagInfo";

export type GitState = { branch: string | null, upstream: string | null, ahead: number | null, behind: number | null, changed: Array<ChangedFile>, recent_commits: Array<CommitInfo>, local_branches: Array<BranchInfo>, remote_branches: Array<RemoteBranchInfo>, tags: Array<TagInfo>, };
