// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PullRequestCommentTarget } from "./PullRequestCommentTarget";
import type { PullRequestDiffSide } from "./PullRequestDiffSide";

export type PullRequestComment = { target: PullRequestCommentTarget, author: string, body: string, created_at: string, updated_at: string, html_url: string, path: string | null, diff_hunk: string | null, line: number | null, side: PullRequestDiffSide | null, start_line: number | null, start_side: PullRequestDiffSide | null, 
/**
 * Present for replies to review-thread comments.
 */
in_reply_to_id: string | null, can_edit: boolean, can_delete: boolean, };
