// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PullRequestRef } from "./PullRequestRef";

export type PullRequestSummary = { pr: PullRequestRef, title: string, url: string, state: string, base_ref: string, head_ref: string, };
