// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PullRequestProvider } from "./PullRequestProvider";

export type PullRequestRef = { provider: PullRequestProvider, host: string, owner: string, repo: string, number: number, };
