// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PullRequestCommentKind } from "./PullRequestCommentKind";

export type PullRequestCommentTarget = { kind: PullRequestCommentKind, 
/**
 * GitHub comment ids can exceed JavaScript's safe integer range, so the
 * protocol carries them as opaque decimal strings.
 */
id: string, };
