// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PullRequestChecksSummary } from "./PullRequestChecksSummary";
import type { PullRequestComment } from "./PullRequestComment";
import type { PullRequestDiffLine } from "./PullRequestDiffLine";
import type { PullRequestFile } from "./PullRequestFile";
import type { PullRequestRef } from "./PullRequestRef";

export type PullRequestDetails = { pr: PullRequestRef, title: string, body: string, author: string, state: string, url: string, base_ref: string, head_ref: string, head_sha: string, is_draft: boolean, labels: Array<string>, reviewers: Array<string>, review_decision: string | null, mergeable: string | null, merge_state_status: string | null, additions: number, deletions: number, changed_files: number, checks: PullRequestChecksSummary, files: Array<PullRequestFile>, comments: Array<PullRequestComment>, diff: Array<PullRequestDiffLine>, };
