// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PullRequestDiffLineKind } from "./PullRequestDiffLineKind";
import type { PullRequestDiffSide } from "./PullRequestDiffSide";

export type PullRequestDiffLine = { path: string, kind: PullRequestDiffLineKind, text: string, old_line: number | null, new_line: number | null, side: PullRequestDiffSide | null, };
