// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary of a base Repository sent to clients for the sidebar tree.
 */
export type RepositorySummary = { id: string, name: string, path: string, default_branch: string | null, worktree_root: string | null, default_agent: string | null, ssh_host: string | null, workspace_count: number, ready_for_review_count: number, };
