// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttentionLevel } from "./AttentionLevel";

export type WorkspaceSummary = { id: string, name: string, path: string, branch: string | null, ahead: number | null, behind: number | null, dirty_files: number, attention: AttentionLevel, agent_running: boolean, agent_active: boolean, shell_running: boolean, last_activity_unix_ms: number, ssh_host: string | null, repository_id: string | null, base_branch: string | null, ready_for_review: boolean, 
/**
 * Agent chosen for this Workspace at creation: a configured profile name or
 * a raw custom command. `None` = use the client's default agent.
 */
agent: string | null, 
/**
 * True when this Workspace points at a pre-existing folder the user
 * attached rather than a worktree Conduit created. Removing it never
 * touches the directory.
 */
adopted: boolean, };
